spring:
  application:
    name: hilt-backend
  datasource:
    url: ${HILT_BACK_END_DB_URL}
    username: ${HILT_DB_USER}
    password: ${HILT_DB_PSWD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    url: ${HILT_BACK_END_DB_URL}
    user: ${HILT_DB_USER}
    password: ${HILT_DB_PSWD}
    locations: classpath:db/migration

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false




  profiles:
    active: dev

  cloud:
    config:
      label: latest

  config:
    import: configserver:http://localhost:8888
server:
  port: 8785