CREATE TYPE STOCK_TXN_TYPE AS ENUM ('RECEIVE', 'SELL', 'ADJUSTMENT', 'RETURN');
CREATE TABLE stock_transactions (
    transaction_id  INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id INTEGER NOT NULL,
     transaction_type STOCK_TXN_TYPE NOT NULL,
    quantity INTEGER NOT NULL,
    transaction_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (product_id) REFERENCES products(product_id)
);
