CREATE TABLE product_categories (
    category_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category_name VARCHAR(255),
    category_desc VARCHAR(150),
    business_unit_id BIGINT,
    FOREIGN KEY (business_unit_id) REFERENCES business_unit(business_id)
);

INSERT INTO product_categories (category_name, category_desc, business_unit_id) VALUES
-- Categories for Business Unit 1
('Electronics', 'Devices and gadgets', 1),
('Home Appliances', 'Appliances for home use', 1),
('Books', 'Various genres of books', 1),
('Clothing', 'Apparel for all ages', 1),
('Toys', 'Fun and educational toys', 1),

-- Categories for Business Unit 2
('Electronics', 'Devices and gadgets', 2),
('Home Appliances', 'Appliances for home use', 2),
('Books', 'Various genres of books', 2),
('Clothing', 'Apparel for all ages', 2),
('Toys', 'Fun and educational toys', 2),

-- Categories for Business Unit 3
('Electronics', 'Devices and gadgets', 3),
('Home Appliances', 'Appliances for home use', 3),
('Books', 'Various genres of books', 3),
('Clothing', 'Apparel for all ages', 3),
('Toys', 'Fun and educational toys', 3),

-- Categories for Business Unit 4
('Electronics', 'Devices and gadgets', 4),
('Home Appliances', 'Appliances for home use', 4),
('Books', 'Various genres of books', 4),
('Clothing', 'Apparel for all ages', 4),
('Toys', 'Fun and educational toys', 4),

-- Categories for Business Unit 5
('Electronics', 'Devices and gadgets', 5),
('Home Appliances', 'Appliances for home use', 5),
('Books', 'Various genres of books', 5),
('Clothing', 'Apparel for all ages', 5),
('Toys', 'Fun and educational toys', 5),

-- Categories for Business Unit 6
('Electronics', 'Devices and gadgets', 6),
('Home Appliances', 'Appliances for home use', 6),
('Books', 'Various genres of books', 6),
('Clothing', 'Apparel for all ages', 6),
('Toys', 'Fun and educational toys', 6),

-- Categories for Business Unit 7
('Electronics', 'Devices and gadgets', 7),
('Home Appliances', 'Appliances for home use', 7),
('Books', 'Various genres of books', 7),
('Clothing', 'Apparel for all ages', 7),
('Toys', 'Fun and educational toys', 7),

-- Categories for Business Unit 8
('Electronics', 'Devices and gadgets', 8),
('Home Appliances', 'Appliances for home use', 8),
('Books', 'Various genres of books', 8),
('Clothing', 'Apparel for all ages', 8),
('Toys', 'Fun and educational toys', 8),

-- Categories for Business Unit 9
('Electronics', 'Devices and gadgets', 9),
('Home Appliances', 'Appliances for home use', 9),
('Books', 'Various genres of books', 9),
('Clothing', 'Apparel for all ages', 9),
('Toys', 'Fun and educational toys', 9),

-- Categories for Business Unit 10
('Electronics', 'Devices and gadgets', 10),
('Home Appliances', 'Appliances for home use', 10),
('Books', 'Various genres of books', 10),
('Clothing', 'Apparel for all ages', 10),
('Toys', 'Fun and educational toys', 10);