CREATE TYPE BankAccountType AS ENUM ('TRUST', 'CHECKING', 'SAVINGS');
CREATE TYPE BankName AS ENUM ('ABSA', 'FNB', 'STANDARD_BANK', 'INVESTEC');

CREATE TABLE banking_information (
    bank_info_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    employee_id INTEGER NOT NULL,
    bank_name BankName NOT NULL,
    account_name  VARCHAR (150),
    bank_account_type BankAccountType NOT NULL,
    account_number VARCHAR(50),
    branch_code VARCHAR (50),
    FOREIGN KEY (employee_id) REFERENCES business_employees(employee_id) ON DELETE CASCADE ON UPDATE CASCADE
);