CREATE TABLE products (
    product_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_name VARCHAR(255),
    product_desc VARCHAR(150),
    product_price DOUBLE PRECISION,
    product_category_id BIGINT,
    FOREIGN KEY (product_category_id) REFERENCES product_categories(category_id)
);

INSERT INTO products (product_name, product_desc, product_price, product_category_id) VALUES
-- Products for Category 1
('Product A1', 'Description for Product A1', 19.99, 1),
('Product A2', 'Description for Product A2', 29.99, 1),

-- Products for Category 2
('Product B1', 'Description for Product B1', 15.99, 2),
('Product B2', 'Description for Product B2', 25.99, 2),

-- Products for Category 3
('Product C1', 'Description for Product C1', 9.99, 3),
('Product C2', 'Description for Product C2', 19.99, 3),

-- Products for Category 4
('Product D1', 'Description for Product D1', 14.99, 4),
('Product D2', 'Description for Product D2', 24.99, 4),

-- Products for Category 5
('Product E1', 'Description for Product E1', 12.99, 5),
('Product E2', 'Description for Product E2', 22.99, 5),

-- Products for Category 6
('Product F1', 'Description for Product F1', 16.99, 6),
('Product F2', 'Description for Product F2', 26.99, 6),

-- Products for Category 7
('Product G1', 'Description for Product G1', 18.99, 7),
('Product G2', 'Description for Product G2', 28.99, 7),

-- Products for Category 8
('Product H1', 'Description for Product H1', 20.99, 8),
('Product H2', 'Description for Product H2', 30.99, 8),

-- Products for Category 9
('Product I1', 'Description for Product I1', 11.99, 9),
('Product I2', 'Description for Product I2', 21.99, 9),

-- Products for Category 10
('Product J1', 'Description for Product J1', 13.99, 10),
('Product J2', 'Description for Product J2', 23.99, 10),

-- Products for Category 11
('Product K1', 'Description for Product K1', 17.99, 11),
('Product K2', 'Description for Product K2', 27.99, 11),

-- Products for Category 12
('Product L1', 'Description for Product L1', 15.49, 12),
('Product L2', 'Description for Product L2', 25.49, 12),

-- Products for Category 13
('Product M1', 'Description for Product M1', 19.49, 13),
('Product M2', 'Description for Product M2', 29.49, 13),

-- Products for Category 14
('Product N1', 'Description for Product N1', 22.99, 14),
('Product N2', 'Description for Product N2', 32.99, 14),

-- Products for Category 15
('Product O1', 'Description for Product O1', 14.99, 15),
('Product O2', 'Description for Product O2', 24.99, 15),

-- Products for Category 16
('Product P1', 'Description for Product P1', 16.49, 16),
('Product P2', 'Description for Product P2', 26.49, 16),

-- Products for Category 17
('Product Q1', 'Description for Product Q1', 18.49, 17),
('Product Q2', 'Description for Product Q2', 28.49, 17),

-- Products for Category 18
('Product R1', 'Description for Product R1', 21.49, 18),
('Product R2', 'Description for Product R2', 31.49, 18),

-- Products for Category 19
('Product S1', 'Description for Product S1', 10.99, 19),
('Product S2', 'Description for Product S2', 20.99, 19),

-- Products for Category 20
('Product T1', 'Description for Product T1', 12.49, 20),
('Product T2', 'Description for Product T2', 22.49, 20),

-- Products for Category 21
('Product U1', 'Description for Product U1', 14.99, 21),
('Product U2', 'Description for Product U2', 24.99, 21),

-- Products for Category 22
('Product V1', 'Description for Product V1', 16.99, 22),
('Product V2', 'Description for Product V2', 26.99, 22),

-- Products for Category 23
('Product W1', 'Description for Product W1', 9.99, 23),
('Product W2', 'Description for Product W2', 19.99, 23),

-- Products for Category 24
('Product X1', 'Description for Product X1', 14.99, 24),
('Product X2', 'Description for Product X2', 24.99, 24),

-- Products for Category 25
('Product Y1', 'Description for Product Y1', 12.99, 25),
('Product Y2', 'Description for Product Y2', 22.99, 25),

-- Products for Category 26
('Product Z1', 'Description for Product Z1', 16.99, 26),
('Product Z2', 'Description for Product Z2', 26.99, 26),

-- Products for Category 27
('Product AA1', 'Description for Product AA1', 18.99, 27),
('Product AA2', 'Description for Product AA2', 28.99, 27),

-- Products for Category 28
('Product AB1', 'Description for Product AB1', 20.99, 28),
('Product AB2', 'Description for Product AB2', 30.99, 28),

-- Products for Category 29
('Product AC1', 'Description for Product AC1', 11.99, 29),
('Product AC2', 'Description for Product AC2', 21.99, 29),

-- Products for Category 30
('Product AD1', 'Description for Product AD1', 13.99, 30),
('Product AD2', 'Description for Product AD2', 23.99, 30),

-- Products for Category 31
('Product AE1', 'Description for Product AE1', 17.99, 31),
('Product AE2', 'Description for Product AE2', 27.99, 31),

-- Products for Category 32
('Product AF1', 'Description for Product AF1', 15.49, 32),
('Product AF2', 'Description for Product AF2', 25.49, 32),

-- Products for Category 33
('Product AG1', 'Description for Product AG1', 19.49, 33),
('Product AG2', 'Description for Product AG2', 29.49, 33),

-- Products for Category 34
('Product AH1', 'Description for Product AH1', 22.99, 34),
('Product AH2', 'Description for Product AH2', 32.99, 34),

-- Products for Category 35
('Product AI1', 'Description for Product AI1', 14.99, 35),
('Product AI2', 'Description for Product AI2', 24.99, 35),

-- Products for Category 36
('Product AJ1', 'Description for Product AJ1', 16.49, 36),
('Product AJ2', 'Description for Product AJ2', 26.49, 36),

-- Products for Category 37
('Product AK1', 'Description for Product AK1', 18.49, 37),
('Product AK2', 'Description for Product AK2', 28.49, 37),

-- Products for Category 38
('Product AL1', 'Description for Product AL1', 21.49, 38),
('Product AL2', 'Description for Product AL2', 31.49, 38),

-- Products for Category 39
('Product AM1', 'Description for Product AM1', 10.99, 39),
('Product AM2', 'Description for Product AM2', 20.99, 39),

-- Products for Category 40
('Product AN1', 'Description for Product AN1', 12.49, 40),
('Product AN2', 'Description for Product AN2', 22.49, 40),

-- Products for Category 41
('Product AO1', 'Description for Product AO1', 14.99, 41),
('Product AO2', 'Description for Product AO2', 24.99, 41),

-- Products for Category 42
('Product AP1', 'Description for Product AP1', 16.99, 42),
('Product AP2', 'Description for Product AP2', 26.99, 42),

-- Products for Category 43
('Product AQ1', 'Description for Product AQ1', 9.99, 43),
('Product AQ2', 'Description for Product AQ2', 19.99, 43),

-- Products for Category 44
('Product AR1', 'Description for Product AR1', 14.99, 44),
('Product AR2', 'Description for Product AR2', 24.99, 44),

-- Products for Category 45
('Product AS1', 'Description for Product AS1', 12.99, 45),
('Product AS2', 'Description for Product AS2', 22.99, 45),

-- Products for Category 46
('Product AT1', 'Description for Product AT1', 16.99, 46),
('Product AT2', 'Description for Product AT2', 26.99, 46),

-- Products for Category 47
('Product AU1', 'Description for Product AU1', 18.99, 47),
('Product AU2', 'Description for Product AU2', 28.99, 47),

-- Products for Category 48
('Product AV1', 'Description for Product AV1', 20.99, 48),
('Product AV2', 'Description for Product AV2', 30.99, 48),

-- Products for Category 49
('Product AW1', 'Description for Product AW1', 11.99, 49),
('Product AW2', 'Description for Product AW2', 21.99, 49),

-- Products for Category 50
('Product AX1', 'Description for Product AX1', 13.99, 50),
('Product AX2', 'Description for Product AX2', 23.99, 50);
