CREATE TABLE business_employees (
    employee_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    employee_number VARCHAR(50) NOT NULL,
    employee_first_name VARCHAR(100) NOT NULL,
    employee_last_name VARCHAR(100) NOT NULL,
    employee_phone_number VARCHAR(15),
    employee_email_address VARCHAR(100),
     business_unit_id BIGINT,
        FOREIGN KEY (business_unit_id) REFERENCES business_unit(business_id)
);

INSERT INTO business_employees (employee_number, employee_first_name,
employee_last_name, employee_phone_number, employee_email_address, business_unit_id)
VALUES
    ('E001', 'John', 'Doe', '123-456-7890', 'john.doe@example.com',1),
    ('E002', 'Jane', 'Smith', '234-567-8901', 'jane.smith@example.com',1),
    ('E003', 'Michael', 'Johnson', '345-678-9012', 'michael.johnson@example.com',1),
    ('E004', 'Emily', 'Davis', '456-789-0123', 'emily.davis@example.com',1),
    ('E005', 'David', 'Martinez', '567-890-1234', 'david.martinez@example.com',1),
    ('E006', 'Sophia', 'Garcia', '678-901-2345', 'sophia.garcia@example.com',2),
    ('E007', 'James', 'Wilson', '789-012-3456', 'james.wilson@example.com',2),
    ('E008', 'Olivia', 'Anderson', '890-123-4567', 'olivia.anderson@example.com',2),
    ('E009', 'Liam', 'Thomas', '901-234-5678', 'liam.thomas@example.com',2),
    ('E010', 'Ava', 'Taylor', '012-345-6789', 'ava.taylor@example.com',2);