CREATE TABLE business_branches (
    branch_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    branch_name VARCHAR(255),
    branch_location VARCHAR(150),
    business_unit_id BIGINT,
    FOREIGN KEY (business_unit_id) REFERENCES business_unit(business_id)
);

INSERT INTO business_branches (branch_name, branch_location, business_unit_id)
VALUES ('SunningHill Branch', 'SunningHill', 1)