

CREATE TABLE departments (
    department_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    department_name VARCHAR(50) NOT NULL,
    department_desc VARCHAR(150) NOT NULL,
    business_unit_id BIGINT,
    FOREIGN KEY (business_unit_id) REFERENCES business_unit(business_id) ON UPDATE CASCADE
);

INSERT INTO departments (department_name, department_desc, business_unit_id)
VALUES ('marketing', 'Marketing department', 1);

ALTER TABLE business_employees
ADD COLUMN department_id INTEGER;

ALTER TABLE business_employees
ADD CONSTRAINT fk_department
FOREIGN KEY (department_id) REFERENCES departments(department_id) ON UPDATE CASCADE;

UPDATE business_employees SET department_id = 1;

ALTER TABLE business_employees
DROP CONSTRAINT IF EXISTS business_employees_business_unit_id_fkey;

ALTER TABLE business_employees DROP COLUMN business_unit_id;
