CREATE TABLE product_stock  (
    product_stock_id  INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id INTEGER NOT NULL,
    total_quantity INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (product_id) REFERENCES products(product_id)
);

INSERT INTO product_stock (product_id, total_quantity) VALUES (1, 1876);
